# Generated by Django 3.1.2 on 2020-10-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
