# Generated by Django 3.1.2 on 2020-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20201024_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('M.C.A', 'M.C.A'), ('B.C.A', 'B.C.A'), ('B.A', 'B.A'), ('M.A', 'M.A'), ('P.G', 'P.G'), ('HIGH SCHOOL', 'HIGH SCOOL'), ('SECONDARY', 'SECONDARY')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
