# Generated by Django 3.1.2 on 2020-10-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_auto_20201025_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
