# Generated by Django 3.1.2 on 2020-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20201025_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, default='default.png', upload_to='coverimage'),
        ),
    ]
