# Generated by Django 3.1.2 on 2020-10-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_auto_20201025_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_gallary',
            field=models.FileField(blank=True, null=True, upload_to='gallary'),
        ),
    ]
