# Generated by Django 3.1.2 on 2020-10-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_profile_photo_gallary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo_gallary',
        ),
    ]
