# Generated by Django 3.1.2 on 2020-10-30 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_photogallary'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallary',
            name='upload_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
