# Generated by Django 3.1.2 on 2020-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_photogallary_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallary',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
