# Generated by Django 3.1.2 on 2020-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_auto_20201103_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_gallary',
            field=models.FileField(blank=True, null=True, upload_to='gallaries'),
        ),
        migrations.DeleteModel(
            name='PhotoGallary',
        ),
    ]
